### ISSUE TITLE
Bug: when extension page is opened, cannot manage extensions

### ISSUE THREAD

**Issue by rnemec** [stef-levesque/vscode-hexdump#29]
Reproduce:
* Go to Extensions
* click on any extension (e.g. uninstalled one)
* opening the page produces the error below
* trying to "Install" or "Update" the extension from the summary page, doesn't work

The error in the log (copied from Dev Tools):
```
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at vscode.window.onDidChangeActiveTextEditor (/Users/rnemec/.vscode/extensions/slevesque.vscode-hexdump-1.3.0/out/src/extension.js:82:14)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:346482
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:30930)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:34737)
    at t.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:300894)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:266424)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:154927)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:155604)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError @ shell.ts:474
(anonymous) @ shell.ts:434
e.onUnexpectedError @ errors.ts:68
o @ errors.ts:88
t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by stef-levesque** [comment]
Hm, I can see the error in the Debug Tools, but this is not preventing me from managing the tools.

Validating `e` in [extension.ts#L95](https://github.com/stef-levesque/vscode-hexdump/blob/02ba787cc607c56de97365bbca8b479f5ba5a0cb/src/extension.ts#L95) seems to fix it.
```typescript
vscode.window.onDidChangeActiveTextEditor((e) => {
    if (e && e.document.languageId === 'hexdump') {
        statusBarItem.show();
    } else {
        statusBarItem.hide();
    }
});
```
I'll push a new version tonight.

**Comment by rnemec** [comment]
Thank you. To be honest, I am not sure **what** is preventing me to install/update extensions from the page. Went with the most promising path - the error. Let me get your update and see - maybe that's a report to the vscode team...
